spring.application.name=account-service
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/accounts_db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/bank-realm

app.config.keycloak.server-url=http://localhost:8181
app.config.keycloak.realm=bank-realm
app.config.keycloak.client-id=client-backend
app.config.keycloak.client-secret=aUVKPNyLzfmd2uyfhpwf29ADFwsahnhE

spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer