spring.application.name=gateway-service
server.port=8080

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
spring.main.web-application-type=reactive

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/bank-realm

## Eureka
spring.cloud.gateway.server.webflux.routes[0].id=discovery-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8761
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/eureka
spring.cloud.gateway.server.webflux.routes[0].filters[0]=SetPath=/

## Eureka static resources
spring.cloud.gateway.server.webflux.routes[1].id=discovery-service-static
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8761
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/eureka/**
