version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - bank_db:/var/lib/mysql

  discovery:
    build:
      context: ./discovery
      dockerfile: Dockerfile
    container_name: discovery
    ports:
      - "8761:8761"
    depends_on:
      - db

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - db
      - discovery

  currency-converter:
    build:
      context: ./currency-converter
      dockerfile: Dockerfile
    container_name: currency-converter
    env_file:
      - .env
    ports:
      - "8084:8084"
    depends_on:
      - db

  mail:
    build:
      context: ./mail
      dockerfile: Dockerfile
    container_name: mail
    env_file:
      - .env
    ports:
      - "8082:8082"
    depends_on:
      - db

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth
    env_file:
      - .env
    ports:
      - "8081:8081"
      - "5006:5006"
    depends_on:
      - db

  bank:
    build:
      context: ./bank
      dockerfile: Dockerfile
    container_name: bank
    env_file:
      - .env
    ports:
      - "8083:8083"
      - "5005:5005"
    depends_on:
      - db

volumes:
  bank_db: