version: "3.8"

services:
  db:
    image: mysql:5.7
    container_name: mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - bank_db:/var/lib/mysql

  discovery:
    build:
      context: ./discovery
      dockerfile: Dockerfile
    container_name: discovery
    ports:
      - "8761:8761"
    depends_on:
      - db

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - db
      - discovery

  currency-converter:
    build:
      context: ./currency-converter
      dockerfile: Dockerfile
    container_name: currency-converter
    env_file:
      - .env
    ports:
      - "8084:8084"
    depends_on:
      - db
      - discovery

volumes:
  bank_db: