services:
  bank_db:
    container_name: bank_db
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - bank_db:/var/lib/mysql
    networks:
      - ms_network

networks:
  ms_network:
    driver: bridge

volumes:
  bank_db: