services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'bank_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - bank_db:/var/lib/mysql

volumes:
  bank_db: