spring.application.name=currency-converter-service
server.port=8084

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.jackson.deserialization.use-big-decimal-for-floats=true

currency.provider=fxRates

token.api.invertexto=${TOKEN_API_INVERTEXTO}
token.api.fxrates=${TOKEN_API_FXRATESAPI}