spring.application.name=api-gateway
server.port=8080

eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
spring.main.web-application-type=reactive

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/bank-realm/protocol/openid-connect/certs

springdoc.enable-native-support=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config

springdoc.swagger-ui.urls[0].name=API Gateway
springdoc.swagger-ui.urls[0].url=/v3/api-docs

springdoc.swagger-ui.urls[1].name=Bank Service
springdoc.swagger-ui.urls[1].url=/bank-api/v3/api-docs

springdoc.swagger-ui.urls[2].name=Currency Service
springdoc.swagger-ui.urls[2].url=/currency-converter-api/v3/api-docs

springdoc.swagger-ui.urls[3].name=Mail Service
springdoc.swagger-ui.urls[3].url=/mail-api/v3/api-docs

## Eureka
spring.cloud.gateway.routes[0].id=discovery-service
spring.cloud.gateway.routes[0].uri=http://discovery:8761
spring.cloud.gateway.routes[0].predicates[0]=Path=/eureka
spring.cloud.gateway.routes[0].filters[0]=SetPath=/

## Eureka static resources
spring.cloud.gateway.routes[1].id=discovery-service-static
spring.cloud.gateway.routes[1].uri=http://discovery:8761
spring.cloud.gateway.routes[1].predicates[0]=Path=/eureka/**

## Bank api
spring.cloud.gateway.routes[2].id=bank-api
spring.cloud.gateway.routes[2].uri=lb://bank-api
spring.cloud.gateway.routes[2].predicates[0]=Path=/bank-api/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

## Currency converter api
spring.cloud.gateway.routes[3].id=currency-converter-api
spring.cloud.gateway.routes[3].uri=lb://currency-converter-api
spring.cloud.gateway.routes[3].predicates[0]=Path=/currency-converter-api/**
spring.cloud.gateway.routes[3].filters[0]=StripPrefix=1

## Mail api
spring.cloud.gateway.routes[4].id=mail-api
spring.cloud.gateway.routes[4].uri=lb://mail-api
spring.cloud.gateway.routes[4].predicates[0]=Path=/mail-api/**
spring.cloud.gateway.routes[4].filters[0]=StripPrefix=1