ALTER TABLE tb_transactions
  ADD COLUMN sender_email VARCHAR(255) DEFAULT NULL,
  ADD COLUMN sender_name VARCHAR(255) DEFAULT NULL,
  ADD COLUMN receiver_email VARCHAR(255) DEFAULT NULL,
  ADD COLUMN receiver_name VARCHAR(255) DEFAULT NULL;
