spring.application.name=currency-converter-api
server.port=8084

eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs

server.forward-headers-strategy=framework

keycloak.auth-url=http://localhost:8181/realms/bank-realm/protocol/openid-connect/auth
keycloak.token-url=http://localhost:8181/realms/bank-realm/protocol/openid-connect/token

token.api.invertexto=${TOKEN_API_INVERTEXTO}