spring.application.name=user-service
server.port=8085

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

app.config.keycloak.server-url=http://localhost:8181
app.config.keycloak.realm=bank-realm
app.config.keycloak.client-id=user-ms-client
app.config.keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/bank-realm

app.config.gateway-url=http://localhost:8080/user-service